### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by emmalait** [juhoaj/tsoha-taagi#2]
ZIP-paketti ladattu 15.2. klo 17.22

### Dokumentointi
* Dokumentointi on pääsääntöisesti selkeää ja helppolukuista.
* Reitit.md-tiedoston reittilistaukset ovat hiukan sekavia, en esim. alkuun ymmärtänyt X/XX/XXX-merkintöjen markitystä keskellä reittien kuvauksia. Ehkä tätä voisi selkiyttää tekemällä näistä listan sijaan taulukon, jossa esim. metodi ja reitti, funktio, template ja X/XX/XXX-merkinnät ovat kukin omissa kolumneissaan ja miettimällä reittien esitysjärjestystä. Hienoa joka tapauksessa että nämä on dokumentoitu!
* Käyttäjätapausten backlog/done-jaottelusta selviää helposti sovelluksen tämänhetkinen tila.

### Toiminnallisuus
* Pyörii sekä Herokussa että paikallisesti.
* Kaikki dokumentaation käyttötapauksiin valmiiksi merkityt toiminnallisuudet ovat toimivia eli sovellukseen voi rekisteröityä ja kirjautua sisään, kirjautumisen jälkeen näkyy lista kaikista viesteistä ja listaan voi lisätä uuden viestin.
* Näiden lisäksi Hallinta-linkin takaa pääsee Tagien hallintaan, jossa näkyy tagilistaus. Tageja voi myös lisätä ja muokata, mutta poistaminen ei toistaiseksi toimi.
* Paikalliseksi ladatussa versiossa viesteihin voi jo lisätä tageja, tätä ei vielä ollut Heroku-sovelluksessa.

### Koodi
* Sovelluksen koodi on järjestetty paketteihin ja tiedostot nimetty samaa logiikkaa noudattaen.
* Plussaa kommenteista reitteihin liittyen views-tiedostoissa, ne parantavat koodin luettavuutta.
* Validointeja käytössä ViestiFormissa, mutta ei (ainakaan vielä) esim. SignupFormissa. Nyt on esim. mahdollista luoda kaksi samannimistä käyttäjää.
* .gitignoreen jäänyt esimerkin tietokanta (tasks.db) ja Gitissä sen vuoksi mukana tietokanta.
* Bootstrap otettu käyttöön
* [AChecker](https://achecker.ca/checker/index.php) antaa vain muutamia known problem -herjoja esim. puuttuvasta/virheellisestä dokumenttikielen määrittelystä.
* Pieni note: layout.html:ssä <header>-tiedossa TodoApp

Kaiken kaikkiaan tähän asti oikein toimiva sovellus. Käyttäjätapausten todo-listasta ei kunnianhimoa puutu :)

**Comment by juhoaj** [comment]
Kiitoksia vielä kommenteista!
