### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by sainikumara** [juhoaj/tsoha-taagi#3]
# Vertaisarviointi II

Vertaisarvioitava projekti ladattu 26.2.2019 kello 22:16

## Testaus

Yritin rekisteröidä tunnuksen, mutta se olikin jo käytössä. Sovellus heitti minut kirjautumissivulle sen sijaan että olisin jäänyt samalle sivulle ja päässyt yrittämään heti uudestaan. Hetken ihmettelyn jälkeen ("Luo uusi käyttäjä"-teksti oli hypännyt eri puolelle) toki löysin taas tieni rekisteröitymissivulle ja sain käyttäjätunnuksen luotua. Tässä vaiheessa ohjauduin etusivulle, enkä suinkaan kirjautumissivulle, jossa olisin voinut heti hyödyntää uutta tunnustani.

Hämmennyin välillä hetkeksi siitä, ettei näkymässä ollut yhtään visuaalisesti selkeitä nappeja.

Arvostan, että olet ehtinyt toteuttaa sivutuksen. Olisi vielä hienompaa, jos voisin avata sivulla 2 viestin ja palata siitä takaisin sivulle 2 jotain sivulla olevaa nappia painamalla. Nyt päädyn viestistä takaisin etusivulle, ellen käytä selaimen back-nappia.

Kyky antaa ylläpitäjästatus itselleni tuntui yllättävältä. :)

Ylläpitäjänä menin katsomaan käyttäjälistausta, mutta sieltä puuttuu se tunnus, jota en voinut aluksi rekisteröidä, koska se on jo käytössä. Erikoista.

Mahdollisuus lisätä tageja viestille viesin luomisen jälkeen olisi jees.

Saavutettavuudesta sen verran, että turkoosi väri näyttää kivalta, mutta sen ja valkoisen taustan välinen kontrasti on vain 2.78. Korkeampi kontrastisuhde olisi parempi.

## Dokumentaatio

Dokumentaatio on hyvin kattava, siinä on paljon sellaista, mitä en olisi ikinä keksinyt kysyäkään. Kaikin osin se ei aivan noudata kurssilla esiteltyä terminologiaa (esim. käyttäjätapaukset = käyttötapaukset/user storyt -> käyttäjätarinat?, auktorisointi = autorisointi?)

Dokumentaatio ei sikäli täysin vastaa sovelluksen nykyistä vaihetta, että melkein joka kohdassa on mukana myös sovelluksen suunniteltuja ominaisuuksia. Esim. tietokantakaaviosta ei minulle heti käynyt ilmi, onko käyttäjän ja tagin välillä tällä hetkellä yhteyttä vai ei; eli voisi vielä lisää joissain kohdissa tarkentaa, mikä kaikki on nyt olemassa ja mitä vasta suunnitellaan.

Olisi ollut tosi kiinnostavaa lukea, miksi ja miten päädyit tekemään frontin suhteen niitä valintoja, joita teit. Fronttipuoleen vaikuttaa olevan panostettu kovasti, ja tämän kurssin tietojen perusteella siitä on vaikea ottaa kovin tarkasti selvää.

Yritin asentaa ohjelman paikallisesti asennusohjeesi mukaisesti, mutta riippuvuuksien asennusyritys johti virheeseen:
```
   Complete output from command python setup.py egg_info:
    Error: typed_ast only runs on Python 3.3 and above.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-R8fmws/typed-ast/
```
Tällä koneella on Python 3.5.2, joten en ihan tiedä, mistä on kyse.

Yritin asentaa ne uudestaan virtuaaliympäristön luonnin ja aktivoinnin jälkeen, sain erilaisia virheilmoituksia melkoisen listan, mutta sen jälkeen sovellus lähti kuin lähtikin käyntiin!

## Koodi

Koodi noudattaa rakenteeltaan ja nimeämiskäytännöiltään kurssilla opittua.

En ole varma, pitäisikö/kannattaisiko tietokantahakujen olla pääasiassa view-tiedostoissa vai model-tiedostoissa.

Validointeja on hyvin! Olet myös jaksanut hienosti kirjoittaa kaikenlaiset virheviestit suomeksi, kun käyttöliittymän kieli on suomi.

Jotkin funktion nimet eivät ihan ensivilkaisulla paljasta, mitä funktio tekee: esim. kayttaja_muokkaa_uusi ja kayttaja. Jotkin muut sen sijaan ainakin minulle tuntuvat avautuvan paremmin, esim. vastaus_uusi ja viesti_uusi.

Saavutettavuustesti achecker.ca varoittaa, että <title>-elementti on <head>-elementin ulkopuolella ja html-dokumentin kieltä ei ole määritelty.

Ihan virkistävää, että navigointipalkki puuttuu kokonaan. Joissain tapauksissa kuitenkin voisi vielä miettiä, missä olisi paras sijainti millekin toiminnolle.

Osa commit-viesteistä todella informatiivisia: esim. "tagin muokkausnäkymässä defaultina tagin nimi". Osa taas ei varsinaisesti, esim. "nätitetty"

**Comment by juhoaj** [comment]
Kiitoksia todella kattavista kommenteista! Noista on ollut huomattavasti apua kun sovelluksessa on repsottanut vielä aika moni nurkka..
